import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const frontendRoot = path.resolve(__dirname, "..");

const nftArtifactPath = path.resolve(
  frontendRoot,
  process.env.NFT_ARTIFACT_PATH ?? "../contracts/artifacts/contracts/MiladyNFT.sol/MiladyNFT.json"
);

const marketplaceArtifactPath = path.resolve(
  frontendRoot,
  process.env.MARKETPLACE_ARTIFACT_PATH ?? "../contracts/artifacts/contracts/MiladyMarketplace.sol/MiladyMarketplace.json"
);

const outputPath = path.resolve(frontendRoot, "src/lib/abis.ts");

function loadAbi(artifactPath, label) {
  if (!fs.existsSync(artifactPath)) {
    return { ok: false, error: `${label} artifact not found at ${artifactPath}` };
  }

  try {
    const raw = fs.readFileSync(artifactPath, "utf8");
    const artifact = JSON.parse(raw);

    if (!Array.isArray(artifact.abi)) {
      return { ok: false, error: `${label} artifact is missing an abi array` };
    }

    return { ok: true, abi: artifact.abi };
  } catch (error) {
    return {
      ok: false,
      error: `${label} artifact could not be parsed: ${error instanceof Error ? error.message : String(error)}`,
    };
  }
}

function buildOutput(nftAbi, marketplaceAbi) {
  const nft = JSON.stringify(nftAbi, null, 2);
  const marketplace = JSON.stringify(marketplaceAbi, null, 2);

  return `// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-abis.mjs from contract artifacts.

export const MILADY_NFT_ABI = ${nft} as const;

export const MILADY_MARKETPLACE_ABI = ${marketplace} as const;
`;
}

const nft = loadAbi(nftArtifactPath, "MiladyNFT");
const marketplace = loadAbi(marketplaceArtifactPath, "MiladyMarketplace");

if (!nft.ok || !marketplace.ok) {
  if (!nft.ok) {
    console.warn(`[abi:sync] ${nft.error}`);
  }
  if (!marketplace.ok) {
    console.warn(`[abi:sync] ${marketplace.error}`);
  }
  console.warn("[abi:sync] Keeping existing frontend/src/lib/abis.ts unchanged.");
  process.exit(0);
}

const output = buildOutput(nft.abi, marketplace.abi);
fs.writeFileSync(outputPath, output, "utf8");
console.log(`[abi:sync] Updated ${outputPath}`);
